### ISSUE TITLE
[Bug]  constructCloudinaryUrl only produces a url to an image, missing video

### ISSUE THREAD

**Issue by Max29a** [colbyfayock/next-cloudinary#115]
# **Bug Report**
Trying to use constructCloudinaryUrl to build a url to a video

## **Describe the bug**
I have this code:
```
const videoSrc = constructCloudinaryUrl({
        options: {
            src: myUrl,
            width: 300
        },
    });
```
This url produced is: 
`https://res.cloudinary.com/my_cloud/image/upload/c_limit,w_300/f_auto/q_auto/v1/my_bucket/y4ank5eyjertifyf3fmx.mp4?_a=AVASxBx0`

As you can see the `image` part of the above path is wrong, it should instead be `video`. I thought passing `deliveryType: "video"` might solve it but that produces: `https://res.cloudinary.com/my_cloud/image/video/c_limit,w_300/f_auto/q_auto/v1/my_bucket/y4ank5eyjertifyf3fmx.mp4?_a=AVASxBx0`

## **Expected behaviour**
It should produce: `https://res.cloudinary.com/my_cloud/video/upload/c_limit,w_300/f_auto/q_auto/v1/my_bucket/y4ank5eyjertifyf3fmx.mp4?_a=AVASxBx0`

Perhaps its this line in the source: 
```
return cldImage.setDeliveryType((options == null ? void 0 : options.deliveryType) || 'upload').format((options == null ? void 0 : options.format) || 'auto').delivery("q_" + ((options == null ? void 0 : options.quality) || 'auto')).toURL({
```

**Comment by colbyfayock** [comment]
hey @Max29a - yeah as you saw it's hardcoded as images right now. i hadn't got to video yet so didn't consider that. this should be easy to add as an option though

that said, and sorry to pull out the rug from under you (funny timing), i just moved constructCloudinaryUrl over to a different repository with a goal of using this abstraction for other frameworks

i created a new ticket with the above over there: https://github.com/colbyfayock/cloudinary-util/issues/6

you can use the function with the latest after installing `@cloudinary-util/url-loader` with

```
import { constructCloudinaryUrl } from '@cloudinary-util/url-loader';
```

beyond that, thinking about implementation, do you have any thought as to what you would expect this to do?

I could see trying to infer the asset type if passed in a full URL, but can't do that if `src` is a public ID

i could do:
```
const videoSrc = constructCloudinaryUrl({
        options: {
            src: myUrl,
            width: 300,
            assetType: 'video'
        },
    });
```

since that would fall along the lines of the cloudinary naming conventions

thoughts?

**Comment by colbyfayock** [comment]
oh and last thing - what are you using as a video? i may try to add a CldVideoPlayer component that wraps the Cloudinary Video Player:

https://cloudinary.com/documentation/cloudinary_video_player

similar to what this library is currently doing with CldUploadWidget 

would that be interesting to you?

**Comment by Max29a** [comment]
I should preface my response with the fact that I am brand new to both NextJS and Cloudinary. So thanks for making it easy for me to work with! I think passing `assetType` in the options makes perfect sense. Currently I am just using a plain old `<video>` tag. My next step was to start looking into what Next offers. I am using `CldUploadWidget` so I would love if there was a `CldVideoPlayer`.

**Comment by colbyfayock** [comment]
im gonna close this issue and work on it from Cloudinary Util (per link above) if you wanted to watch that one isntead

I also created a ticket for adding a video player

https://github.com/colbyfayock/next-cloudinary/issues/116

let me know if you have any other ideas for features or feedback youd like to see

**Comment by colbyfayock** [comment]
hey @Max29a been a minute but video support is now available via https://github.com/colbyfayock/cloudinary-util/issues/6
