### ISSUE TITLE
[Bug] Won't trigger state changes after navigation

### ISSUE THREAD

**Issue by dannycallaghan** [colbyfayock/next-cloudinary#128]
I've just implemented the excellent CldUploadWidget into my Next project and have found that if you visit a page that has the widget, then navigate away, then return, the widget won't trigger any further changes to React state.

For example, consider the following code:

```
const [attempts, setAttempts] = useState(0);
const [error, setError] = useState();

const handleUpload = (error, result, widget) => {
    setAttempts(prev => prev + 1);
    if (error) {
      console.error(`Error: ${result.statusText}`);
      setError(result.statusText);
    }
};
```
The first time that you use the widget, when handleUpload is called, the error and attempts state is successfully updated. If you then navigate to another page, and then return to the widget, the state will not get updated again.

You can see this bug occurring here:

[https://next-cloudinary-bug-self.vercel.app](https://next-cloudinary-bug-self.vercel.app)

Steps to reproduce:

1. Click on 'Upload widget'.
2. Attempt to upload a file (the environment variables are obviously fake, so this will trigger an error).
3. Note that the attempts counter gets incremented, and the error text is displayed. Notice that the error text is also displayed in the browser console.
4. Navigate to the home or 'another' page.
5. Return to the widget.
6. Attempt to upload a file.
7. Note that the console display the error, but neither the attempts not error state is updated and the changes displayed to the page.

You can view the complete code here:

[https://github.com/dannycallaghan/next-cloudinary-bug](https://github.com/dannycallaghan/next-cloudinary-bug)

I have found that the state updater function doesn't even get called (I first assumed that the state was changing, but either react didn't see the difference between the old state and the new, or just wasn't re-rendering the component). I checked this by doing:

```
setAttempts(prev => {
  console.log('Attempting to update state');
  return prev + 1;
})
```
The log message doesn't get called.

I suspect this has something to do with the script and the iframe already being placed in the DOM the first time around? But no idea how to fix it.

Thanks. Great widget by the way.

**Comment by dannycallaghan** [comment]
Hello again

Any thoughts on this? Seems like a pretty fundamental issue.

Thanks

**Comment by colbyfayock** [comment]
This is a strange one, i've been throwing in some console logs and was able to easily reproduce it in the Docs website

![image](https://user-images.githubusercontent.com/1045274/220813057-dd993d57-87e9-413a-9bb7-8f450c58a525.png)

those logs are probably tough to decipher haha but:
```
<CldUploadWidget
  uploadPreset="next-cloudinary-unsigned"
  onUpload={(error, result, widget) => {
    console.log('onUpload', result);
    console.log('setResource', setResource);
```

the thing that's interesting to me is that callback IS firing and it is seeing a `setResource` function, but it's almost as if it lost its connection to the state instance?

going to now jump into a rabbit hole of googling around and seeing what i can find but nothing seems obvious to me thus far

im hesitant to think it's related to the script tag and / or the iframe because from my understanding, I'm not doing anything that should, from my understanding, impact the relationship between the setter function and the wrapper of the upload widget, as at that point, thats just plain react, but i may be wrong there

**Comment by colbyfayock** [comment]
hey @dannycallaghan mind taking a look at this PR and seeing what you think? https://github.com/colbyfayock/next-cloudinary/pull/138

I'm not crazy about switching to useEffect and adding that additional layer, but it's the only solution I can think of right now, and it seems to work reliably from testing it

the deployed Docs site preview works for testing

**Comment by dannycallaghan** [comment]
Hi @colbyfayock 

> as if it lost its connection to the state instance?

Yes, exactly!

Thanks for your work on this. I've taken a look at the PR, and all looks good, but I have to admit that I'm not sure how to test this myself, if that's what you were hoping for before merging!

**Comment by colbyfayock** [comment]
thanks @dannycallaghan
