### ISSUE TITLE
[Bug] Cannot open Signed UploadWidget

### ISSUE THREAD

**Issue by mcoeur** [colbyfayock/next-cloudinary#158]
# **Bug Report**

## **Describe the bug**

When clicking on the button to open the UploadWidget, nothing happens and an error triggers : `p.current.open is not a function`

## **Is this a regression?**

I don't know, this is my first time using this package

## **Steps To Reproduce the error**

1. Create a `<CldUploadWidget />` component, just like mentioned in the documentation
2. Click the "Upload an Image" button

## **CodeSandbox or Live Example of Bug**

The bug is actually present on the official documentation page :
https://next-cloudinary.spacejelly.dev/components/clduploadwidget/examples

## **Screenshot or Video Recording**

[![Video recording](https://i.gyazo.com/5a8d1d6b61fed3048d4cb3241197781e.gif)](https://gyazo.com/5a8d1d6b61fed3048d4cb3241197781e)

### **Your environment**

- OS: MacOS
- Node version: 16.13.1
- Npm version: 8.1.2
- Browser name and version: Chrome - 111.0.5563.64

**Comment by colbyfayock** [comment]
hey thanks for the bug report. turns out it wasn't quite a bug, i was missing my api key on the docs deployment 🤦 

that said i did have an optional chaining fix to the right spot to avoid the error you were seeing and added a warning for people like me who forgot to add that :)

not sure if you're just reporting this from the docs or from your own usage but that should address the issue, let me know if you're seeing anything else after it's merged/deployed
