### ISSUE TITLE
Error: (0 , U.useState) is not a function or its return value is not iterable

### ISSUE THREAD

**Issue by tnt-cloudinary** [colbyfayock/next-cloudinary#226]
Hey hey!
Super excited to incorporate this library into my NextJS app.

I've set up a simple NextJS starter app, but when to add a <CldImage /> component to the page I get an Unhandled Runtime Error

Error: (0 , U.useState) is not a function or its return value is not iterable

Here's my code so far:
https://github.com/CloudinaryLtd/next-cloudinary-nextjs-starter

**Comment by colbyfayock** [comment]
hey @tnt-cloudinary - sounds like you're using the Next.js App Router (app directory)

Because of how Next.js works now between server and client components, and the components included require clientside functionality, they need to be marked with a `"use client"` directive at the top of the file you're using them in.

It might make the most sense to create a simple wrapper component inside of your app that includes both this component and that directive to avoid making an entire page clientside, reducing the benefits of serevr compoennts

some more info here https://next-cloudinary.spacejelly.dev/guides/nextjs-13

hoping to make this easier for people in the future once i figure out a way, but in the meantime, let me know if you think there's a good spot i can make this requirement more clear for people
