### ISSUE TITLE
[Bug] Videos not loading on iOS devices

### ISSUE THREAD

**Issue by jwm0** [colbyfayock/next-cloudinary#234]
# **Bug Report**
Videos not loading on iOS devices
## **Describe the bug**
Video player shows a "No supported media sources" on iOS devices

Stack trace:
```
/cloudinary-video-player@1.9.4/dist/cld-video-player.min.js

TypeError
this.videojs.perSourceBehaviors is not a function. (In 'this.videojs.perSourceBehaviors()', 'this.videojs.perSourceBehaviors' is an instance of Object)
```

## **Steps To Reproduce the error**

1. Upload a video to cloudinary or use a sample one
2. Use CldVideoComponent:
```
    <CldVideoPlayer
      width="100%"
      height="auto"
      quality={100}
      src="<public-id>"
      logo={false}
      autoPlay="on-scroll"
      className="shadow-xl xl:rounded-xl"
      colors={{
        accent: "#4f46e5",
        base: "#111827",
        text: "#ffffff",
      }}
    />
```
3. Open on iOS device

## **Expected behaviour**

The video is loaded and played properly

## **Screenshot or Video Recording**

![image](https://github.com/colbyfayock/next-cloudinary/assets/28310983/85468d75-95cb-43ce-888e-276e6e29f82f)

### **Your environment**

- OS: iOS 16.3
- Browser name and version: Safari (iOS 16.3)

**Comment by jwm0** [comment]
Looks like the issue is caused by using `quality={100}` which is unrelated to this library. Using `quality="auto:best"` does the trick. The error in the original post is still being triggered though.

**Comment by colbyfayock** [comment]
hey @jwm0 do you have an example URL that was produced that I can share with the team to ask about this?

i know `quality={100}` doesn't necessarily mean the original quality in how the backend determines what to serve, so i'm wondering if something strange is going on there

for the CldImage component, i implemented the value of `default` which would not apply the quality param given it defaults to `auto`, not sure if thats the use case you were looking for but seems like that would be helpful to apply here as well

**Comment by colbyfayock** [comment]
Got a response from the team

When using q100, you're request the video to be returned as lossless which means its not going to automatically return a format/codec that works for any browser/device like auto would. It actually ends up inflating the video size sometimes, so you likely wouldn't want to use that as the option anyways.

so that said - in iOS safari, that source isn't playable which leads to that error which stems from the Cloudinary Video Player project

unfortunately i dont think there's anything i could do on my end to make this a better experience, just that q100 is not the recommended approach for most cases, and like you've found, using something like `auto:best` instead
