### ISSUE TITLE
[Bug] Images with spaces in filename are incorrectly parsed

### ISSUE THREAD

**Issue by lhguerra** [colbyfayock/next-cloudinary#235]
Cloudinary delivers spaces in image names like this:
https://res.cloudinary.com/myaccount/image/upload/vnumber/foo%20bar.png

Where the %20 is the space. And when I use this url in the CldImage component, it breaks the url:
https://res.cloudinary.com/myaccount/image/upload/c_limit,w_70/f_webp/q_auto/vnumber/foo%2520bar

It transforms %20 to %2520 which breaks the url and is not found by cloudinary

**Comment by colbyfayock** [comment]
hey @lhguerra what version are you on? I fixed a similar issue, i'm wondering if perhaps a simple upgrade might fix this 🤞 

https://github.com/colbyfayock/next-cloudinary/issues/219
https://github.com/colbyfayock/next-cloudinary/pull/232

**Comment by lhguerra** [comment]
I'm using the latest version 4.15.0

**Comment by colbyfayock** [comment]
hey @lhguerra sorry about that - in the package the constructs the URLs, the fix wasn't pulled in from one of its dependencies due to a bit of an inconsistent deployment setup that I need to separately figure out.

it should now be working on the latest, added a test to validate, but pleasel et me know if you still notice issues

**Comment by lhguerra** [comment]
Worked like a charm! Thanks again for the fast update!
