### ISSUE TITLE
[Bug] CldUploadWidget with multiple in options returns only one image on callback

### ISSUE THREAD

**Issue by bogmihut8** [colbyfayock/next-cloudinary#285]
Hello,

I'm using CldUploadWidget to implement multiple images upload at once. Having set as options maxFiles and multiple, I am expecting the callback to return a list of images, after the upload was successful, but I am still receiving only the first image in the callback's return. Here is the code, any tip or information is very appreciated. Maybe there is something I am missing, but I haven't found it :(

```
"use client";

import { CldUploadWidget } from "next-cloudinary";
import Image from "next/image";
import React, { useCallback } from "react";
import { TbPhotoPlus } from "react-icons/tb";

declare global {
  var cloudinary: any;
}

type Props = {
  onChange: (value: string[]) => void;
  value: string[];
};

function ImageUpload({ onChange, value }: Props) {
  const handleCallback = useCallback(
    (result: any) => {
      console.log(result); // <---- I should receive a list of images here, but I am seeing only the first one
      onChange(result.info.secure_url);
    },
    [onchange]
  );

  return (
    <CldUploadWidget
      onUpload={handleCallback}
      uploadPreset="xxxxxxxxxxx"
      options={{
        maxFiles: 10,
        multiple: true
      }}
    >
      {({ open }) => {
        return (
          <div
            onClick={() => open?.()}
            className=" relative cursor-pointer hover:opacity-70 transition border-dashed border-2 p-20 border-neutral-300 flex flex-col justify-center items-center gap-4 text-neutral-600"
          >
            <TbPhotoPlus size={50} />
            <div className="font-semibold text-lg">Click to upload</div>
            {value && (
              <div className=" absolute inset-0 w-full h-full">
                <Image
                  alt="uploade"
                  fill
                  style={{ objectFit: "cover" }}
                  src={value}
                />
              </div>
            )}
          </div>
        );
      }}
    </CldUploadWidget>
  );
}

export default ImageUpload;
```

**Comment by colbyfayock** [comment]
hey @bogmihut8 thanks for your patience in me getting back to you

i was just testing this out and it looks like what's happening is the success callback, which fires `onUpload` gets called multiple times, one for each successful upload:

```
onUpload={(result, widget) => {
  console.log('onUploadresult', result)
}}
```

<img width="655" alt="image" src="https://github.com/colbyfayock/next-cloudinary/assets/1045274/84fa731f-f2ad-49f9-ae3e-84e1afbd69ef">

you can see that its different files by the `id` there

do you see the same thing when uploading multiple files? the callback being called multiple times?

in this situation you'd likely want to have an instance of state that updates and append each result to make available for you as a group

alternatively, i've somewhat recently added support for all native widget events including `onQueuesEnd` which will fire once at the end of the uploading process

<img width="588" alt="image" src="https://github.com/colbyfayock/next-cloudinary/assets/1045274/7637d829-ef08-4ac1-80ce-baf45170f522">

this may actually be what you want instead

```
onQueuesEnd={(result, widget) => {
  console.log('result', result)
}}
```

but still, id be curious if `onUpload` is not working or if you're seeing the multple callbacks like im seeing

im considering deprecating `onUpload` in the future because of the confusion which will allow me to point to the Cloudinary docs for the official representation, but i think thats beside the current point

**Comment by bogmihut8** [comment]
Hello @colbyfayock, thank you so much for your response.

In my case, as in yours, it happens exactly the same: **onUpload** will trigger with each uploaded file and its object, while **onQueuesEnd** will prompt all the files as an array and will be triggered when the process finishes.

Closing this as your suggestion is exactly what I need. Cheers!
