### ISSUE TITLE
[Bug] Sizes property not working with full prop

### ISSUE THREAD

**Issue by lhguerra** [colbyfayock/next-cloudinary#295]
# **Bug Report**

## **Describe the bug**

When using the full prop (Next's way of making the image fluid) combined with the sizes prop, CldImage component doesn't generate the alternative urls for the different viewports, they're all the same.

## **Steps To Reproduce the error**

1. Add any image with CldImage component
2. Add the fill prop, and not width and height
3. Add the sizes prop
4. The srcset attribute has many urls but they're all the same

## **Expected behaviour**

One url with different width for each viewport in the sizes prop.

## **Screenshot or Video Recording**
With CldImage all the links are the same:
![272616127-dc1ecbbb-ce34-4a2e-a0e5-74d6ed36fdc5](https://github.com/colbyfayock/next-cloudinary/assets/4529663/79685740-24c2-4b8d-a20e-e10ae677b665)

With Next Image the srcset is correctly generated according to the sizes prop:
![272616173-184c45e2-8b9b-4bc0-b8c2-bec11555ef6d](https://github.com/colbyfayock/next-cloudinary/assets/4529663/853e7139-1d9c-486a-9b13-c7d8bfab08e9)

**Comment by colbyfayock** [comment]
hey @lhguerra if you care to give the change a second pair of eyes, it's available in this PR: https://github.com/colbyfayock/next-cloudinary/pull/297

otherwise I'll get this merged soon to get the fix out

i was able to confirm the responsive sizing is showing up in the deploy preview with the Fill example

https://next-cloudinary-l0ojm8zk3-cloudinarydevx.vercel.app/cldimage/examples#fill

**Comment by lhguerra** [comment]
I have no familiarity with the lib's code so I have no comments on patterns or stuff like that, but the code makes sense and looks well tested too! Just approved it.

**Comment by colbyfayock** [comment]
haha all good, appreciate you taking a quick look!
