### ISSUE TITLE
[Bug] Build error on 5.13.0 and newer

### ISSUE THREAD

**Issue by PhilipAngelinNE** [colbyfayock/next-cloudinary#387]
# **Bug Report**

## **Describe the bug**

We have a monorepo with several apps. One uses app router, and there are no issues with building the app.
However another one that uses pages router, gets the following build error on 5.13.0 or newer only:
```
info  - Collecting page data ...Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/philip/projects/mono/node_modules/next/image' imported from /home/philip/projects/mono/node_modules/next-cloudinary/dist/index.mjs
Did you mean to import next/image.js?
    at finalizeResolution (node:internal/modules/esm/resolve:255:11)
    at moduleResolve (node:internal/modules/esm/resolve:908:10)
    at defaultResolve (node:internal/modules/esm/resolve:1121:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:396:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:365:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
    at link (node:internal/modules/esm/module_job:84:36) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///home/philip/projects/mono/node_modules/next/image'
}
```

## **Is this a regression?**

Yes, since this does not happen before 5.13.0.

### **Your environment**

- OS: Windows 11 | 23H2 (but this also happens on our GitHub bots that use Linux).
- Node version: 20.10.0
- Npm version: 10.2.3

**Comment by colbyfayock** [comment]
ill see if i can reproduce this, havent seen this one yet. what package manager / monorepo tooling are you using?

**Comment by colbyfayock** [comment]
looks like this isn't a mono-repo specific issue its a Pages router issue

<img width="1127" alt="image" src="https://github.com/colbyfayock/next-cloudinary/assets/1045274/e928c3d4-1af6-4cd7-abe8-76516a0cdb16">

i suspect its related to foundational work to set up subpath imports via https://github.com/colbyfayock/next-cloudinary/pull/370/files

will see what i can find

**Comment by colbyfayock** [comment]
seems to be a known issue with regards to ESM for the next/image component. trying these workarounds: https://github.com/vercel/next.js/issues/54777#issuecomment-1808505837

**Comment by colbyfayock** [comment]
getting somewhere with:

```
import { Image } from 'next/dist/client/image-component.js';
```


but now running into the same issue with Head

<img width="1075" alt="image" src="https://github.com/colbyfayock/next-cloudinary/assets/1045274/e4dc2003-c0be-4d3d-92ed-883783532479">

i dont think i'll be comfortable pushing this out right before the holidays either way since it feels like a risky fix, for now hopefully keeping it pinned to a lower version is sufficient

**Comment by colbyfayock** [comment]
You could potentially try using them the same way with a ts-ignore above each prop. They technically should get passed through I believe just not typed

**Comment by colbyfayock** [comment]
looping back around to this, im struggling to get all of the imports working properly, particularly, i guess due to how the Head components exports are set up, i'm having issues with React, which i suspect is due to multiple versions which is creating an issue for consumer apps using it

i'm not having much luck finding a solution so my intent at this time is to work on a #363 and introduce a breaking change in the CldVideoPlayer component where for Pages apps, requires manually importing the CSS file, similar to how it would be required in the App directory

CldOgImage still uses the Head component, so im unsure if that will be impacted as well, but will have to see as im digging through everything

**Comment by colbyfayock** [comment]
update: im going to revert the subpath changes for 5.x as they were never documented and add those base in 6.x as part of an overall breaking change

**Comment by colbyfayock** [comment]
@PhilipAngelinNE should be good to go with 5.17.0 which reverts the import changes and should include the latest other features. please let me know if you run into any issues, i appreciate your patience

**Comment by mbifulco** [comment]
Worked like a charm for me - thanks @colbyfayock!
